import type { Metadata } from "next";
import { AppSidebar } from "../../components/app-sidebar";
import {
  Breadcrumb,
  BreadcrumbItem,
  BreadcrumbList,
  BreadcrumbPage,
} from "../../components/ui/breadcrumb";
import { Separator } from "../../components/ui/separator";
import {
  SidebarInset,
  SidebarProvider,
  SidebarTrigger,
} from "../../components/ui/sidebar";
import FileUpload from "../../components/fileUpload";
import { SignOutButton } from "@clerk/nextjs";
import { SearchForm } from "../../components/search-form-public";
import { LogOut } from "lucide-react";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Dropbox",
  description: "Generated by create next app",
  icons: { icon: "/logo.svg", apple: "/logo.svg" },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main>
      <SidebarProvider>
        <AppSidebar />
        <SidebarInset>
          <header className="flex h-16 shrink-0 items-center gap-2 border-b px-4">
            <SidebarTrigger className="-ml-1" />
            <Separator
              orientation="vertical"
              className="mr-2 data-[orientation=vertical]:h-4"
            />

            <SearchForm />
            <div className="mx-auto mr-1.5">
              <FileUpload />
            </div>
            <div className="mt-1">
              <Link href="/">
                <SignOutButton>
                  <LogOut className="size-5 hover:text-red-400 transition-colors duration-200" />
                </SignOutButton>
              </Link>
            </div>
          </header>
          {children}
        </SidebarInset>
      </SidebarProvider>
    </main>
  );
}
